### ISSUE TITLE
大阪府, 兵庫県の搬送先とその搬送患者数のグラフが出力されていない.

### ISSUE THREAD

**Issue by tanaka-hiroki1989** [clinfo/2020_Patients_Transport#2]
- [ ] 他に当該グラフが出力されていない都道府県を調べる.
- [ ] Transport.pyのデバッグ
- [ ] 再度グラフを出力

**Comment by yuji0001** [comment]
これは，今回の予測結果では，大阪，兵庫のベット上限を超えていないので，搬送してないからです．
なので，空のグラフが出力されてregendで警告が出てます．
