### ISSUE TITLE
resultCの可視化(Visualization_Severe.py)での問題点

### ISSUE THREAD

**Issue by tanaka-hiroki1989** [clinfo/2020_Patients_Transport#22]
Visualization_Severe.pyの実行時に次の問題点が見受けられましたので簡単に記述します.
- [x] 過去の全ての時点について画像を作り直してしまう.
- [x] 日付なしの画像が更新されない.
（詳細は後ほど追記します.）

**Comment by yuji0001** [comment]
モード設定を戻していませんでした．
修正します．

**Comment by yuji0001** [comment]
修正しましたので閉じます．
